### ISSUE TITLE
Devel branch causing black screen

### ISSUE THREAD

**Issue by darknight111** [JasonJShuler/openpilot#30]
Installing with ssh causing black screen on boot (OP loads up then screen goes black) that will carry over to any other fork of OP (including stock OP).

This happens even after a factory reset of eon and a fresh install.

**Comment by sck-nogas** [comment]
Jason had some health issues recently, so not sure when he might see this. Are you able to SSH into your OP again after it boots, as in the screen is black, but it appears that the OS is running? Maybe we can debug via SSH?

**Comment by darknight111** [comment]
It's okay, I switched to hanabi95's branches. I'm a little surprised no one
else has had this problem.

I hope Jason recovers quickly.

**Comment by deargubel** [comment]
I am also having this issue. I can confirm that the os is booted and ssh is available. How can we troubleshoot this?

**Comment by deargubel** [comment]
root@localhost:/system/comma/home$ tmux a
running once
/comma.sh: line 19: /sys/class/leds/button-backlight/max_brightness: No such file or directory
Using interface 'wlan0'
OK
/data/openpilot has been modified, skipping overlay update installation
/data/openpilot/launch_chffrplus.sh: line 61: echo: write error: Permission denied
dinfo 1920x1080
egl version 1.4
egl w 1920 h 1080
gl version OpenGL ES 3.2 V@145.0 (GIT@I0ac3940325)
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.
{"event": "dirty comma branch", "version": "0.7.4-GM-0.2-release", "dirty": true, "origin": "https://github.com/JasonJShuler/openpilot.git", "branch": "origin/devel", "dirty_files": "", "commit": "f21590fe23a522a85a5b52c6696919fb35a17140", "origin_commit": "f21590fe23a522a85a5b52c6696919fb35a17140"}
Result: Parcel(00000000 00000001   '........')
installed apks {'com.android.providers.telephony': '/system/priv-app/TelephonyProvider/TelephonyProvider.apk', 'com.qti.service.colorservice': '/system/vendor/app/colorservice/colorservice.apk', 'com.qualcomm.shutdownlistner': '/system/app/shutdownlistener/shutdownlistener.apk', 'com.android.documentsui': '/system/a
pp/DocumentsUI/DocumentsUI.apk', 'ai.comma.plus.black': '/data/app/ai.comma.plus.black-1/base.apk', 'ai.comma.plus.frame': '/data/app/ai.comma.plus.frame-1/base.apk', 'com.android.externalstorage': '/system/priv-app/ExternalStorageProvider/ExternalStorageProvider.apk', 'com.qualcomm.qti.telephonyservice': '/system/a
pp/QtiTelephonyService/QtiTelephonyService.apk', 'com.android.defcontainer': '/system/priv-app/DefaultContainerService/DefaultContainerService.apk', 'com.android.pacprocessor': '/system/app/PacProcessor/PacProcessor.apk', 'org.codeaurora.bluetooth': '/system/app/BluetoothExt/BluetoothExt.apk', 'com.qti.qualcomm.data
statusnotification': '/system/app/datastatusnotification/datastatusnotification.apk', 'android': '/system/framework/framework-res.apk', 'cyanogenmod.platform': '/system/framework/org.cyanogenmod.platform-res.apk', 'com.android.backupconfirm': '/system/priv-app/BackupRestoreConfirmation/BackupRestoreConfirmation.apk'
, 'org.codeaurora.ims': '/system/priv-app/ims/ims.apk', 'com.android.statementservice': '/system/priv-app/StatementService/StatementService.apk', 'com.qualcomm.qcrilmsgtunnel': '/system/priv-app/qcrilmsgtunnel/qcrilmsgtunnel.apk', 'com.android.providers.settings': '/system/priv-app/SettingsProvider/SettingsProvider.
apk', 'com.android.sharedstoragebackup': '/system/priv-app/SharedStorageBackup/SharedStorageBackup.apk', 'com.android.printspooler': '/system/app/PrintSpooler/PrintSpooler.apk', 'com.android.frameworks.telresources': '/system/app/telresources/telresources.apk', 'com.android.webview': '/system/app/webview/webview.apk
', 'com.android.inputdevices': '/system/priv-app/InputDevices/InputDevices.apk', 'com.android.keychain': '/system/app/KeyChain/KeyChain.apk', 'org.cyanogenmod.cmsettings': '/system/priv-app/CMSettingsProvider/CMSettingsProvider.apk', 'com.android.packageinstaller': '/system/priv-app/PackageInstaller/PackageInstaller
.apk', 'com.android.proxyhandler': '/system/priv-app/ProxyHandler/ProxyHandler.apk', 'ai.comma.plus.neossetup': '/system/priv-app/NEOSSetup/NEOSSetup.apk', 'com.android.inputmethod.latin': '/system/app/LatinIME/LatinIME.apk', 'com.android.smspush': '/system/app/WAPPushManager/WAPPushManager.apk', 'ai.comma.plus.offr
oad': '/data/app/ai.comma.plus.offroad-2/base.apk', 'com.android.settings': '/system/priv-app/Settings/Settings.apk', 'com.qualcomm.qti.ims': '/system/vendor/app/imssettings/imssettings.apk', 'com.android.vpndialogs': '/system/priv-app/VpnDialogs/VpnDialogs.apk', 'com.android.phone': '/system/priv-app/TeleService/Te
leService.apk', 'com.android.shell': '/system/priv-app/Shell/Shell.apk', 'com.android.location.fused': '/system/priv-app/FusedLocation/FusedLocation.apk', 'com.android.systemui': '/system/priv-app/SystemUI/SystemUI.apk', 'com.android.bluetoothmidiservice': '/system/app/BluetoothMidiService/BluetoothMidiService.apk',
 'com.qualcomm.fastdormancy': '/system/app/fastdormancy/fastdormancy.apk', 'com.android.bluetooth': '/system/app/Bluetooth/Bluetooth.apk', 'com.qualcomm.timeservice': '/system/app/TimeService/TimeService.apk', 'com.android.development': '/system/app/Development/Development.apk', 'com.qualcomm.embms': '/system/app/em
bms/embms.apk', 'com.android.captiveportallogin': '/system/app/CaptivePortalLogin/CaptivePortalLogin.apk'}
comparing version of ai.comma.plus.black  3e77042a72eadf465ec3c577ebe3cb9cef4e48bb vs 3e77042a72eadf465ec3c577ebe3cb9cef4e48bb
comparing version of ai.comma.plus.frame  1fb19b4c5d3b1ce471dfb7b1789f0042c9894b3e vs 1fb19b4c5d3b1ce471dfb7b1789f0042c9894b3e
comparing version of ai.comma.plus.offroad  72d0f6f0b66515aba8def180cf5140df94b9e6e3 vs 72d0f6f0b66515aba8def180cf5140df94b9e6e3
getting pilotauth
failed to authenticate
Traceback (most recent call last):
  File "/data/openpilot/selfdrive/registration.py", line 54, in register
    dongle_id, access_token = dongleauth["dongle_id"], dongleauth["access_token"]
KeyError: 'access_token'
Traceback (most recent call last):
  File "./manager.py", line 537, in <module>
    main()
  File "./manager.py", line 515, in main
    manager_init()
  File "./manager.py", line 354, in manager_init
    raise Exception("server registration failed")
Exception: server registration failed

**Comment by deargubel** [comment]
I have a white panda and I'm not sure if that matters but I can get it to work properly with manager.py:
def manager_init(should_register=False):
